### ISSUE TITLE
how to export the results

### ISSUE THREAD

**Issue by rc15june** [CrowdStrike/CAST#19]
If we run the script on multiple systems via PSFalcon, how can we get the results of all those systems? Is there anyway? or we need to run on each system at a time?

**Comment by bk-cs** [comment]
If you're exporting to json, you'll need to collect each json from the devices. If you save it to the same path, you can `get` it from all of the devices at the same time.

Or, you can create a script that will export the results to another system. The community edition of Humio is a good location, and if you're interested in that, I have written a script that will export the results there.

**Comment by G3nrlPs0** [comment]
@bk-cs This is a great topic, as our organization is trying to do the same thing using PSFalcon to run CAST on a batch of hosts (which I can get to work), but struggling on how to get all those files back via a batch. I was trying to get the Invoke-FalconBatchGet command to work in PSFalcon for grabbing files (same filename and path across all hosts), but no success. I know this may not be the appropriate forum for this, but if you know of a script or link you could refer us too on the topic of using 'get' for multihost file collection, it's much appreciated. 🙏 (I could inquire via a Crowdstrike support case too if that's the way to go.) Thanks!

**Comment by bk-cs** [comment]
@G3nrIPs0 https://github.com/CrowdStrike/psfalcon/wiki/Commands#use-real-time-response-to-download-a-file

In my opinion, if you're able to use it, exporting the results to Humio is a better choice instead of collecting the results from each machine.

[Humio Community Edition](https://cloud.community.humio.com/) is free and includes more than enough resources to handle your CAST results. Here's a script that could be used to output the results to Humio:

```
if (-not(Test-Path -Path 'C:\cast.exe')) {
    throw "Cannot find path 'C:\cast.exe' because it does not exist."
}
$Param = @{
    FilePath               = 'C:\cast.exe'
    ArgumentList           = 'scan C:\'
    RedirectStandardOutput = 'C:\cast.json'
}
Start-Process @Param -PassThru | ForEach-Object {
    "[$($_.Id): $($_.ProcessName)] Search started. Check Humio for results."
    $Script = {
        param($Id)
        Wait-Process -Id $Id
        $Fields = @{
            host   = [System.Net.Dns]::GetHostname()
            script = 'CastToHumio.ps1'
        }
        if (Test-Path 'C:\cast.json') {
            $Request = @{
                Uri     = 'my_raw_ingest_url'
                Method  = 'post'
                Headers = @{
                    Authorization = 'bearer my_ingest_token'
                    ContentType   = 'application/json'
                }
                Body    = @{
                    fields   = $Fields
                    messages = @((Get-Content 'C:\cast.json').Normalize() -Split '\n' | ForEach-Object {
                        $_ | ConvertFrom-Json
                    })
                }
            }
            $Request.Body = ConvertTo-Json -InputObject $Request.Body -Compress
            [void] (Invoke-WebRequest @Request -UseBasicParsing)
            Remove-Item -Path 'C:\cast.json'
        }
        if (Test-Path -Path 'C:\cast.exe') {
            Remove-Item -Path 'C:\cast.exe'
        }
    }
    Start-Process -FilePath powershell.exe -ArgumentList "-Command &{ $Script } -Id $($_.Id)"
}
```
The script requires `C:\cast.exe`, (so you'd `put` it using Real-time Response beforehand), and you can save it to your Real-time Response Custom Scripts library once you replace `my_ingest_url` and `my_ingest_token` with the appropriate values. When the script runs, it outputs the `cast.exe` results to `C:\cast.json`, and there's a secondary process that's created that waits for the results, then sends them off and deletes the json file when complete.

The ingest token you're using should have the `Json` parser assigned to reduce any error messages during ingestion into Humio.

**Comment by G3nrlPs0** [comment]
@bk-cs This is great information. Thank you!
