### ISSUE TITLE
how to validate script was successful

### ISSUE THREAD

**Issue by rc15june** [CrowdStrike/CAST#26]
Below is the output I get. Does it mean script ran fine and nothing found?

stderr | stdout
-- | --
2022/01/10 16:15:40 archives: 3 found: 0   scanned: 22673 skip: 0 | Searching 65 directories...

**Comment by rbcrwd** [comment]
Do you see `found: 0`? That means exactly what it says.

**Comment by rc15june** [comment]
It rans for only few seconds and get that result. Was is successful?

**Comment by rbcrwd** [comment]
Success depends entirely on you because I know nothing about the context in which you ran it. Was the [lack of] findings what you expected?  If it says it found nothing and the exit code is zero, it found nothing and it didn't encounter a problem during execution, the same as every other executable out there.
